/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.motorph.ui.HRUser;

/**
 *
 * @author sipal
 */
public class pnlAttendance extends javax.swing.JPanel {

    /**
     * Creates new form pnlAttendance
     */
    public pnlAttendance() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAttendance = new javax.swing.JLabel();
        txtSearchAttendance = new javax.swing.JTextField();
        scrollAttendance = new javax.swing.JScrollPane();
        tblAttendance = new javax.swing.JTable();
        btnSearchAttendance = new javax.swing.JButton();
        btnImportAttendance = new javax.swing.JButton();
        btnViewAttendance = new javax.swing.JButton();
        btnRefreshAttendance = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblAttendance.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAttendance.setForeground(new java.awt.Color(0, 51, 102));
        lblAttendance.setText("Attendance Record");

        txtSearchAttendance.addActionListener(this::txtSearchAttendanceActionPerformed);

        tblAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee Name", "Date", "Time In", "Tine Out", "Total Hours", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollAttendance.setViewportView(tblAttendance);

        btnSearchAttendance.setText("Search");
        btnSearchAttendance.addActionListener(this::btnSearchAttendanceActionPerformed);

        btnImportAttendance.setText("Import");

        btnViewAttendance.setText("View");

        btnRefreshAttendance.setText("Refresh");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnImportAttendance)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewAttendance)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefreshAttendance))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblAttendance)
                            .addGap(597, 597, 597))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtSearchAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSearchAttendance)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(scrollAttendance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(lblAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchAttendance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollAttendance, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImportAttendance)
                    .addComponent(btnViewAttendance)
                    .addComponent(btnRefreshAttendance))
                .addContainerGap(142, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchAttendanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchAttendanceActionPerformed

    private void btnSearchAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAttendanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchAttendanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImportAttendance;
    private javax.swing.JButton btnRefreshAttendance;
    private javax.swing.JButton btnSearchAttendance;
    private javax.swing.JButton btnViewAttendance;
    private javax.swing.JLabel lblAttendance;
    private javax.swing.JScrollPane scrollAttendance;
    private javax.swing.JTable tblAttendance;
    private javax.swing.JTextField txtSearchAttendance;
    // End of variables declaration//GEN-END:variables
}
