/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package com.mycompany.motorph.ui.HRUser;

/**
 *
 * @author sipal
 */
public class pnlEmployees extends javax.swing.JPanel {

    /** Creates new form pnlEmployees */
    public pnlEmployees() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmployee = new javax.swing.JLabel();
        scrollEmployee = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        btnAddEmployee = new javax.swing.JButton();
        btnUpdateEmployee = new javax.swing.JButton();
        btnDeleteEmployee = new javax.swing.JButton();
        txtSearchEmployee = new javax.swing.JTextField();
        btnSearchEmployee = new javax.swing.JButton();
        btnGovtIDInfo = new javax.swing.JButton();
        lblEmployees = new javax.swing.JLabel();

        lblEmployee.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmployee.setForeground(new java.awt.Color(0, 51, 102));
        lblEmployee.setText("Employee");

        setBackground(new java.awt.Color(255, 255, 255));

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Number", "Last Name", "First Name", "Position", "Status", "Basic Salary", "Hourly Rate", "Phone Number", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollEmployee.setViewportView(tblEmployee);

        btnAddEmployee.setText("Add Employee");
        btnAddEmployee.addActionListener(this::btnAddEmployeeActionPerformed);

        btnUpdateEmployee.setText("Update Employee");

        btnDeleteEmployee.setText("Delete Employee");

        txtSearchEmployee.addActionListener(this::txtSearchEmployeeActionPerformed);

        btnSearchEmployee.setText("Search");
        btnSearchEmployee.addActionListener(this::btnSearchEmployeeActionPerformed);

        btnGovtIDInfo.setText("Government ID Information");
        btnGovtIDInfo.addActionListener(this::btnGovtIDInfoActionPerformed);

        lblEmployees.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmployees.setForeground(new java.awt.Color(0, 51, 102));
        lblEmployees.setText("Employees");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmployees)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddEmployee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateEmployee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteEmployee))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtSearchEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnSearchEmployee)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGovtIDInfo))
                        .addComponent(scrollEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(lblEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchEmployee)
                    .addComponent(btnGovtIDInfo))
                .addGap(33, 33, 33)
                .addComponent(scrollEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddEmployee)
                    .addComponent(btnUpdateEmployee)
                    .addComponent(btnDeleteEmployee))
                .addGap(163, 163, 163))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchEmployeeActionPerformed

    private void btnSearchEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchEmployeeActionPerformed

    private void btnAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddEmployeeActionPerformed

    private void btnGovtIDInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGovtIDInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGovtIDInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEmployee;
    private javax.swing.JButton btnDeleteEmployee;
    private javax.swing.JButton btnGovtIDInfo;
    private javax.swing.JButton btnSearchEmployee;
    private javax.swing.JButton btnUpdateEmployee;
    private javax.swing.JLabel lblEmployee;
    private javax.swing.JLabel lblEmployees;
    private javax.swing.JScrollPane scrollEmployee;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTextField txtSearchEmployee;
    // End of variables declaration//GEN-END:variables

}
