/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.motorph.ui.HRUser;

/**
 *
 * @author sipal
 */
public class pnlReports extends javax.swing.JPanel {

    /**
     * Creates new form pnlReports
     */
    public pnlReports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblReports = new javax.swing.JLabel();
        txtSearchReports = new javax.swing.JTextField();
        btnReports = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnGenerateReport = new javax.swing.JButton();
        btnExportReport = new javax.swing.JButton();
        btnRefreshReports = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblReports.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblReports.setForeground(new java.awt.Color(0, 51, 102));
        lblReports.setText("Reports");

        txtSearchReports.addActionListener(this::txtSearchReportsActionPerformed);

        btnReports.setText("Search");
        btnReports.addActionListener(this::btnReportsActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Report ID", "Report Type", "Generate By", "Date", "Description/Remarks"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnGenerateReport.setText("Generate Report");

        btnExportReport.setText("Export/Download");
        btnExportReport.addActionListener(this::btnExportReportActionPerformed);

        btnRefreshReports.setText("Refresh");
        btnRefreshReports.addActionListener(this::btnRefreshReportsActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGenerateReport)
                        .addGap(18, 18, 18)
                        .addComponent(btnExportReport)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefreshReports))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSearchReports, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReports))
                    .addComponent(lblReports)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lblReports, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchReports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReports))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerateReport)
                    .addComponent(btnExportReport)
                    .addComponent(btnRefreshReports))
                .addContainerGap(179, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchReportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchReportsActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnRefreshReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshReportsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshReportsActionPerformed

    private void btnExportReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExportReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportReport;
    private javax.swing.JButton btnGenerateReport;
    private javax.swing.JButton btnRefreshReports;
    private javax.swing.JButton btnReports;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblReports;
    private javax.swing.JTextField txtSearchReports;
    // End of variables declaration//GEN-END:variables
}
